apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: anonymous
  deployment:
    accessible_namespaces: ["**"]
    view_only_mode: true
  server:
    web_root: "/kiali"
  external_services:
    prometheus:
      url: http://prometheus-server.monitoring:80/